### ISSUE TITLE
Inconsistencies between different types of quotes

### ISSUE THREAD

**Issue by muster-mark** [jimkang/split-to-words#1]
I am aware of the complication of the fact that the same character is used for both single curly quotes and apostrophes. However, the below inconsistencies between different types of quotes seems like a bug.

`"Split" to words` -> ["Split", "to", "words"]
`“Split” to words` -> ["“Split”, "to", "words"]
`‘Split’ to words` -> ["‘Split’, "to", "words"]
`'Split' to words` -> ["'Split'", "to", "words]

**Comment by jimkang** [comment]
Hey, thanks for noticing! Yeah, a quote probably shouldn't be considered a word boundary, so I updated it to not do that. It should consider quotes and quote-like characters to be part of the word in 2.0, which I just published.
